@extends('spark::layouts.app')

@section('title',config('app.name').': Glossary')

@section('content')
      <div class="title">
          Acronyms &amp; Glossary
      </div>
      <div class="subtitle m-b-md">
          Common Terms and Definitions
      </div>

      <div class="container text-left">
        <h3>Acronyms</h3>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">CFR</div><div class="col-xs-8">Code of Federal Regulations</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">CIO</div><div class="col-xs-8">Chief Information Officer</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">CNSS</div><div class="col-xs-8">Committee on National Security Systems</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">CUI</div><div class="col-xs-8">Controlled Unclassified Information</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">FIPS</div><div class="col-xs-8">Federal Information Processing Standards</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">FISMA</div><div class="col-xs-8">Federal Information Security Modernization Act</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">ISO/IEC</div><div class="col-xs-8">International Organization for Standardization/International Electrotechnical Commission</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">ISOO</div><div class="col-xs-8">Information Security Oversight Office</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">ITL</div><div class="col-xs-8">Information Technology Laboratory</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">NARA</div><div class="col-xs-8">National Archives and Records Administration</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">NFO</div><div class="col-xs-8">Nonfederal Organization</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">NIST</div><div class="col-xs-8">National Institute of Standards and Technology</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">OMB</div><div class="col-xs-8">Office of Management and Budget</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">SP</div><div class="col-xs-8">Special Publication</div></div>
      </div>

      <div class="container text-left">
        <h3>Glossary</h3>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	agency	</div><div class="col-xs-8">	See executive agency.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	assessment	</div><div class="col-xs-8">	See Security Control Assessment.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	assessor	</div><div class="col-xs-8">	See Security Control Assessor.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	audit log	</div><div class="col-xs-8">	A chronological record of system activities, including records of system accesses and operations performed in a given period.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	audit record	</div><div class="col-xs-8">	An individual entry in an audit log related to an audited event.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	authentication	</div><div class="col-xs-8">	Verifying the identity of a user, process, or device, often as a prerequisite to allowing access to resources in a system.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	availability	</div><div class="col-xs-8">	Ensuring timely and reliable access to and use of information.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	baseline configuration	</div><div class="col-xs-8">	A documented set of specifications for a system, or a configuration item within a system, that has been formally reviewed and agreed on at a given point in time, and which can be changed only through change control procedures.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	blacklisting	</div><div class="col-xs-8">	A process used to identify software programs that are not authorized to execute on a system or prohibited Universal Resource Locators (URL)/websites.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	confidentiality	</div><div class="col-xs-8">	Preserving authorized restrictions on information access and disclosure, including means for protecting personal privacy and proprietary information.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	configuration management	</div><div class="col-xs-8">	A collection of activities focused on establishing and maintaining the integrity of information technology products and systems, through control of processes for initializing, changing, and monitoring the configurations of those products and systems throughout the system development life cycle.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	configuration settings	</div><div class="col-xs-8">	The set of parameters that can be changed in hardware, software, or firmware that affect the security posture and/or functionality of the system.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	controlled area	</div><div class="col-xs-8">	Any area or space for which the organization has confidence that the physical and procedural protections provided are sufficient to meet the requirements established for protecting the information or system.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	controlled unclassified information	</div><div class="col-xs-8">	Information that law, regulation, or governmentwide policy requires to have safeguarding or disseminating controls, excluding information that is classified under Executive Order 13526, Classified National Security Information, December 29, 2009, or any predecessor or successor order, or the Atomic Energy Act of 1954, as amended.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	CUI categories or subcategories	</div><div class="col-xs-8">	Those types of information for which laws, regulations, or government wide policies require or permit agencies to exercise safeguarding or dissemination controls, and which the CUI Executive Agent has approved and listed in the CUI Registry.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	CUI Executive Agent	</div><div class="col-xs-8">	The National Archives and Records Administration (NARA), which implements the executive branch-wide CUI Program and oversees federal agency actions to comply with Executive Order 13556. NARA has delegated this authority to the Director of the Information Security Oversight Office (ISOO).	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	CUI program	</div><div class="col-xs-8">	The executive branch-wide program to standardize CUI handling by all federal agencies. The program includes the rules, organization, and procedures for CUI, established by Executive Order 13556, 32 CFR Part 2002, and the CUI Registry.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	CUI registry	</div><div class="col-xs-8">	The online repository for all information, guidance, policy, and requirements on handling CUI, including everything issued by the CUI Executive Agent other than 32 CFR Part 2002. Among other information, the CUI Registry identifies all approved CUI categories and subcategories, provides general descriptions for each, identifies the basis for controls, establishes markings, and includes guidance on handling procedures.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	environment of operation	</div><div class="col-xs-8">	The physical surroundings in which a system processes, stores, and transmits information.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	executive agency	</div><div class="col-xs-8">	An executive department specified in 5 U.S.C., Sec. 105; a military department specified in 5 U.S.C., Sec. 102; an independent establishment as defined in 5 U.S.C., Sec. 104(1); and a wholly owned Government corporation fully subject to the provisions of 31 U.S.C., Chapter 91.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	external system (or component)	</div><div class="col-xs-8">	A system or component of a system that is outside of the authorization boundary established by the organization and for which the organization typically has no direct control over the application of required security controls or the assessment of security control effectiveness.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	external system service	</div><div class="col-xs-8">	A system service that is implemented outside of the authorization boundary of the organizational system (i.e., a service that is used by, but not a part of, the organizational system) and for which the organization typically has no direct control over the application of required security controls or the assessment of security control effectiveness.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	external system service provider	</div><div class="col-xs-8">	A provider of external system services to an organization through a variety of consumer-producer relationships including but not limited to: joint ventures; business partnerships; outsourcing arrangements (i.e., through contracts, interagency agreements, lines of business arrangements); licensing agreements; and/or supply chain exchanges.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	external network	</div><div class="col-xs-8">	A network not controlled by the organization.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	federal agency	</div><div class="col-xs-8">	See executive agency.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	federal information system	</div><div class="col-xs-8">	An information system used or operated by an executive agency, by a contractor of an executive agency, or by another organization on behalf of an executive agency.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	FIPS-validated cryptography	</div><div class="col-xs-8">	A cryptographic module validated by the Cryptographic Module Validation Program (CMVP) to meet requirements specified in FIPS Publication 140-2 (as amended). As a prerequisite to CMVP validation, the cryptographic module is required to employ a cryptographic algorithm implementation that has successfully passed validation testing by the Cryptographic Algorithm Validation Program (CAVP). See NSA-Approved Cryptography.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	firmware	</div><div class="col-xs-8">	Computer programs and data stored in hardware - typically in read-only memory (ROM) or programmable read-only memory (PROM) - such that the programs and data cannot be dynamically written or modified during execution of the programs.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">		</div><div class="col-xs-8">		</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	hardware	</div><div class="col-xs-8">	The physical components of a system. See Software and Firmware.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	identifier	</div><div class="col-xs-8">	Unique data used to represent a person’s identity and associated attributes. A name or a card number are examples of identifiers. A unique label used by a system to indicate a specific entity, object, or group.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	impact	</div><div class="col-xs-8">	The effect on organizational operations, organizational assets, individuals, other organizations, or the Nation (including the national security interests of the United States) of a loss of confidentiality, integrity, or availability of information or a system.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	impact value	</div><div class="col-xs-8">	The assessed potential impact resulting from a compromise of the confidentiality of information (e.g., CUI) expressed as a value of low, moderate, or high.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	incident	</div><div class="col-xs-8">	An occurrence that actually or potentially jeopardizes the confidentiality, integrity, or availability of a system or the information the system processes, stores, or transmits or that constitutes a violation or imminent threat of violation of security policies, security procedures, or acceptable use policies.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	information	</div><div class="col-xs-8">	Any communication or representation of knowledge such as facts, data, or opinions in any medium or form, including textual, numerical, graphic, cartographic, narrative, or audiovisual.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	information flow control	</div><div class="col-xs-8">	Procedure to ensure that information transfers within a system are not made in violation of the security policy.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	information resources	</div><div class="col-xs-8">	Information and related resources, such as personnel, equipment, funds, and information technology.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	information security	</div><div class="col-xs-8">	The protection of information and information systems from unauthorized access, use, disclosure, disruption, modification, or destruction in order to provide confidentiality, integrity, and availability.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	information system	</div><div class="col-xs-8">	A discrete set of information resources organized for the collection, processing, maintenance, use, sharing, dissemination, or disposition of information.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	information technology	</div><div class="col-xs-8">	Any equipment or interconnected system or subsystem of equipment that is used in the automatic acquisition, storage, manipulation, management, movement, control, display, switching, interchange, transmission, or reception of data or information by the executive agency. For purposes of the preceding sentence, equipment is used by an executive agency if the equipment is used by the executive agency directly or is used by a contractor under a contract with the executive agency which: (i) requires the use of such equipment; or (ii) requires the use, to a significant extent, of such equipment in the performance of a service or the furnishing of a product. The term information technology includes computers, ancillary equipment, software, firmware, and similar procedures, services (including support services), and related resources.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	insider threat	</div><div class="col-xs-8">	The threat that an insider will use her/his authorized access, wittingly or unwittingly, to do harm to the security of the United States. This threat can include damage to the United States through espionage, terrorism, unauthorized disclosure, or through the loss or degradation of departmental resources or capabilities.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	integrity	</div><div class="col-xs-8">	Guarding against improper information modification or destruction, and includes ensuring information non-repudiation and authenticity.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	internal network	</div><div class="col-xs-8">	A network where establishment, maintenance, and provisioning of security controls are under the direct control of organizational employees or contractors; or the cryptographic encapsulation or similar security technology implemented between organization- controlled endpoints, provides the same effect (with regard to confidentiality and integrity). An internal network is typically organization-owned, yet may be organization-controlled while not being organization-owned.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	least privilege	</div><div class="col-xs-8">	The principle that a security architecture should be designed so that each entity is granted the minimum system resources and authorizations that the entity needs to perform its function.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	local access                            	</div><div class="col-xs-8">	Access to an organizational system by a user (or process acting on behalf of a user) communicating through a direct connection without the use of a network.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	malicious code	</div><div class="col-xs-8">	Software or firmware intended to perform an unauthorized process that will have adverse impact on the confidentiality, integrity, or availability of a system. A virus, worm, Trojan horse, or other code-based entity that infects a host. Spyware and some forms of adware are also examples of malicious code.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	media	</div><div class="col-xs-8">	Physical devices or writing surfaces including, but not limited to, magnetic tapes, optical disks, magnetic disks, Large-Scale Integration (LSI) memory chips, and printouts (but not including display media) onto which information is recorded, stored, or printed within a system.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	mobile code	</div><div class="col-xs-8">	Software programs or parts of programs obtained from remote systems, transmitted across a network, and executed on a local system without explicit installation or execution by the recipient.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	mobile device	</div><div class="col-xs-8">	A portable computing device that has a small form factor such that it can easily be carried by a single individual; is designed to operate without a physical connection (e.g., wirelessly transmit or receive information); possesses local, non-removable/removable data storage; and includes a self-contained power source. Mobile devices may also include voice communication capabilities, on- board sensors that allow the devices to capture information, or built-in features that synchronize local data with remote locations. Examples include smartphones, tablets, and E-readers.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	multifactor authentication	</div><div class="col-xs-8">	Authentication using two or more different factors to achieve authentication. Factors include something you know (e.g., PIN, password); something you have (e.g., cryptographic identification device, token); or something you are (e.g., biometric). See also Authenticator.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	nonfederal organization	</div><div class="col-xs-8">	An entity that owns, operates, or maintains a nonfederal system.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	nonfederal system	</div><div class="col-xs-8">	A system that does not meet the criteria for a federal system.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	network	</div><div class="col-xs-8">	A system implemented with a collection of interconnected components. Such components may include routers, hubs, cabling, telecommunications controllers, key distribution centers, and technical control devices.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	network access	</div><div class="col-xs-8">	Access to a system by a user (or a process acting on behalf of a user) communicating through a network (e.g., local area network, wide area network, Internet).	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	nonlocal maintenance          	</div><div class="col-xs-8">	Maintenance activities conducted by individuals communicating through a network, either an external network (e.g., the Internet) or an internal network.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	on behalf of (an agency)	</div><div class="col-xs-8">	A situation that occurs when: (i) a non-executive branch entity uses or operates an information system or maintains or collects information for the purpose of processing, storing, or transmitting Federal information; and (ii) those activities are not incidental to providing a service or product to the government.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	organization	</div><div class="col-xs-8">	An entity of any size, complexity, or positioning within an organizational structure.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	portable storage device	</div><div class="col-xs-8">	A system component that can be inserted into and removed from a system, and that is used to store data or information (e.g., text, video, audio, and/or image data). Such components are typically implemented on magnetic, optical, or solid state devices (e.g., floppy disks, compact/digital video disks, flash/thumb drives, external hard disk drives, and flash memory cards/drives that contain nonvolatile memory).	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	potential impact	</div><div class="col-xs-8">	The loss of confidentiality, integrity, or availability could be expected to have: (i) a limited adverse effect (FIPS Publication 199 low); (ii) a serious adverse effect (FIPS Publication 199 moderate); or (iii) a severe or catastrophic adverse effect (FIPS Publication 199 high) on organizational operations, organizational assets, or individuals.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	privileged account	</div><div class="col-xs-8">	A system account with authorizations of a privileged user.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	privileged user	</div><div class="col-xs-8">	A user that is authorized (and therefore, trusted) to perform security-relevant functions that ordinary users are not authorized to perform.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	records	</div><div class="col-xs-8">	The recordings (automated and/or manual) of evidence of activities performed or results achieved (e.g., forms, reports, test results), which serve as a basis for verifying that the organization and the system are performing as intended. Also used to refer to units of related data fields (i.e., groups of data fields that can be accessed by a program and that contain the complete set of information on particular items).	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	remote access                        	</div><div class="col-xs-8">	Access to an organizational system by a user (or a process acting on behalf of a user) communicating through an external network (e.g., the Internet).	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	remote maintenance	</div><div class="col-xs-8">	Maintenance activities conducted by individuals communicating through an external network (e.g., the Internet).	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	replay resistance	</div><div class="col-xs-8">	Protection against the capture of transmitted authentication or access control information and its subsequent retransmission with the intent of producing an unauthorized effect or gaining unauthorized access.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	risk	</div><div class="col-xs-8">	A measure of the extent to which an entity is threatened by a potential circumstance or event, and typically a function of: (i) the adverse impacts that would arise if the circumstance or event occurs; and (ii) the likelihood of occurrence. System-related security risks are those risks that arise from the loss of confidentiality, integrity, or availability of information or systems. Such risks reflect the potential adverse impacts to organizational operations, organizational assets, individuals, other organizations, and the Nation.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	risk assessment	</div><div class="col-xs-8">	The process of identifying risks to organizational operations (including mission, functions, image, reputation), organizational assets, individuals, other organizations, and the Nation, resulting from the operation of a system. Part of risk management, incorporates threat and vulnerability analyses, and considers mitigations provided by security controls planned or in place. Synonymous with risk analysis.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	sanitization                           	</div><div class="col-xs-8">	Actions taken to render data written on media unrecoverable by both ordinary and, for some forms of sanitization, extraordinary means. Process to remove information from media such that data recovery is not possible. It includes removing all classified labels, markings, and activity logs.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	security	</div><div class="col-xs-8">	A condition that results from the establishment and maintenance of protective measures that enable an enterprise to perform its mission or critical functions despite risks posed by threats to its use of systems. Protective measures may involve a combination of deterrence, avoidance, prevention, detection, recovery, and correction that should form part of the enterprise’s risk management approach.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	security assessment	</div><div class="col-xs-8">	See Security Control Assessment.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	security control	</div><div class="col-xs-8">	A safeguard or countermeasure prescribed for a system or an organization designed to protect the confidentiality, integrity, and availability of its information and to meet a set of defined security requirements.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	security control assessment	</div><div class="col-xs-8">	The testing or evaluation of security controls to determine the extent to which the controls are implemented correctly, operating as intended, and producing the desired outcome with respect to meeting the security requirements for a system or organization.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	security functionality	</div><div class="col-xs-8">	The security-related features, functions, mechanisms, services, procedures, and architectures implemented within organizational systems or the environments in which those systems operate.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	security functions	</div><div class="col-xs-8">	The hardware, software, or firmware of the system responsible for enforcing the system security policy and supporting the isolation of code and data on which the protection is based.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	security relevance	</div><div class="col-xs-8">	Functions or mechanisms that are relied upon, directly or indirectly, to enforce a security policy that governs confidentiality, integrity, and availability protections.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	split tunneling	</div><div class="col-xs-8">	The process of allowing a remote user or device to establish a non-remote connection with a system and simultaneously communicate via some other connection to a resource in an external network. This method of network access enables a user to access remote devices (e.g., a networked printer) at the same time as accessing uncontrolled networks.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	supplemental guidance	</div><div class="col-xs-8">	Statements used to provide additional explanatory information for security controls or security control enhancements.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	system	</div><div class="col-xs-8">	See Information System.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	system component	</div><div class="col-xs-8">	A discrete, identifiable information technology asset (hardware, software, firmware) that represents a building block of a system. System components include commercial information technology products.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	system security plan	</div><div class="col-xs-8">	A document that describes how an organization meets the security requirements for a system or how an organization plans to meet the requirements. In particular, the system security plan describes the system boundary; the environment in which the system operates; how the security requirements are implemented; and the relationships with or connections to other systems.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	system service	</div><div class="col-xs-8">	A capability provided by a system that facilitates information processing, storage, or transmission.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	threat	</div><div class="col-xs-8">	Any circumstance or event with the potential to adversely impact organizational operations, organizational assets, individuals, other organizations, or the Nation through a system via unauthorized access, destruction, disclosure, modification of information, and/or denial of service.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	user	</div><div class="col-xs-8">	Individual, or (system) process acting on behalf of an individual, authorized to access a system.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	whitelisting	</div><div class="col-xs-8">	A process used to identify software programs that are authorized to execute on a system or authorized Universal Resource Locators (URL)/websites.	</div></div>
        <div class="row hoverable"><div class="col-xs-2 col-xs-offset-2 text-success">	wireless technology	</div><div class="col-xs-8">	Technology that permits the transfer of information between separated points without physical connection.	</div></div>
      </div>

@endsection
