branch-defaults:
  master:
    environment: onesevenone
    group_suffix: null
global:
  application_name: onesevenone
  branch: null
  default_ec2_keyname: null
  default_platform: PHP 7.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
